services:
  database:
    image: postgres
    volumes:
      - ItqGroup-db:/var/lib/postgresql
    environment:
      POSTGRES_DB: ItqGroup
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"


volumes:
  ItqGroup-db: